### PR TITLE
Bump version to 0.1

### PR DESCRIPTION
**Pull request by tmcgilchrist**
@erikd @thumphries 

Bumping to 0.1 from 0.0.2 as it feels feature complete the way it is now. Thoughts?

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Only hold up is https://github.com/tmcgilchrist/transformers-either/pull/10 and whether the API needs to change.

**Comment by thumphries** [comment]
The naming still feels a little ad-hoc to me (`handleEitherT` in particular), but on the other hand I would really like to get `bracketEitherT` out there where I can use it, so :man_shrugging:

I can set aside some time for a renaming proposal if you don't mind the bikeshed. Once we release it, the names are forever

**Comment by erikd** [comment]
Happy to get suggestions for alternatives to `handleEitherT` or any of the others.

**Comment by thumphries** [comment]
Another thing: it looks like `exceptions` now has a real `MonadMask` instance for `ExceptT`.

This may negate the need for all the exception-handling stuff we're considering releasing...

**Comment by tmcgilchrist** [comment]
I haven’t looked at the new exceptions yet.
Would be nice to keep a range of ghc versions supported is my only concern.
That and it works correctly.

**Comment by thumphries** [comment]
that's probably a good point, it will take ages for `exceptions` to bubble down through Hackage/Stackage. It's still not in Stackage Nightly, for example, so few package maintainers will have started reacting to it.

**Comment by erikd** [comment]
I'm fine with this as it is.

**Pull request merged**
