### PR TITLE
Tighten base lower bound to prevent bad build plans on GHC 7.8 and below

### PR DESCRIPTION
**Pull request by gwils**

### CODE REVIEW

**Comment by gwils** [comment]
As a hackage trustee, I have made metadata revisions on all three existing versions to this effect.

**Comment by gwils** [comment]
The (mafia-based) travis build has failed because mafia currently does not support GHC 8.4
I've made a PR for that here https://github.com/haskell-mafia/mafia/pull/220

**Comment by erikd** [comment]
@tmcgilchrist How would you feel about a pure cabal build/test in travis?

This package doesn't have many dependencies, so mafia caching doesn't buy much.

**Comment by gwils** [comment]
I'd certainly like that, and I'd be happy to make the change if Tim is ok with it.
If we use hvr's script for a `new-build` based travis, we'll get caching from that.

**Comment by gwils** [comment]
PR here: https://github.com/tmcgilchrist/transformers-either/pull/17

**Comment by tmcgilchrist** [comment]
Thumbs up!

**Pull request merged**
